CC := mpic++
CFLAGS := -Wall
TARGET := mid3
v := 1

all: $(TARGET)

$(TARGET):F74128206_mid3.cpp
	$(CC) -o $@ $^

judge: all
	@judge -v ${v} || printf "or \`make judge v=1\`"

clean:
	rm -f $(TARGET)
